#!/usr/bin/env python3
"""Generate the committed product-model artifacts from the registry.

Emits `generated/product-model.schema.json`, `generated/index.ts` and
`PRODUCTS.md`. Deterministic: the same registry always produces
byte-identical output (the codegen drift test relies on it).
"""

import argparse
import json
import sys
from pathlib import Path
from typing import Any

PACKAGE_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PACKAGE_ROOT))

from pydantic import BaseModel
from pydantic.json_schema import models_json_schema

from product_model import PRODUCT_KINDS, REGISTRY, ScrapedProduct, ScrapedTransaction

HEADER = (
    "AUTO-GENERATED by packages/product-model/scripts/generate.py — do not edit"
)

_TS_SCALARS = {
    "string": "string",
    "date": "string",
    "integer": "number",
    "number": "number",
    "boolean": "boolean",
}

_MD_SCALARS = {
    "string": "str",
    "date": "date",
    "integer": "int",
    "number": "float",
    "boolean": "bool",
}

_DENOMINATIONS = ("currency", "percent", "count")


class UnsupportedSchemaError(ValueError):
    """A model field uses a construct outside the closed, TS-mappable set."""


def _resolve_type(prop: dict[str, Any], where: str) -> tuple[Any, bool]:
    """Resolve a property schema to (token, nullable).

    Token is a scalar name ("string"/"integer"/"number"/"boolean"/"date") or
    ("const", value). The supported constructs are a closed set; anything
    else raises UnsupportedSchemaError.
    """
    if "anyOf" in prop:
        members = prop["anyOf"]
        nulls = [m for m in members if m.get("type") == "null"]
        others = [m for m in members if m.get("type") != "null"]
        if len(members) != 2 or len(nulls) != 1 or len(others) != 1:
            raise UnsupportedSchemaError(f"{where}: unsupported anyOf {members!r}")
        token, _ = _resolve_type(others[0], where)
        return token, True
    if "const" in prop:
        value = prop["const"]
        if not isinstance(value, str):
            raise UnsupportedSchemaError(f"{where}: non-string const {value!r}")
        return ("const", value), False
    type_ = prop.get("type")
    if type_ == "string":
        fmt = prop.get("format")
        if fmt == "date":
            return "date", False
        if fmt is None:
            return "string", False
        raise UnsupportedSchemaError(f"{where}: unsupported string format {fmt!r}")
    if type_ in ("integer", "number", "boolean"):
        return type_, False
    raise UnsupportedSchemaError(f"{where}: unsupported schema {prop!r}")


def _ts_type(token: Any) -> str:
    if isinstance(token, tuple):
        return json.dumps(token[1], ensure_ascii=False)
    return _TS_SCALARS[token]


def _md_type(token: Any) -> str:
    if isinstance(token, tuple):
        return json.dumps(token[1], ensure_ascii=False)
    return _MD_SCALARS[token]


def _ordered_properties(schema: dict[str, Any]) -> list[tuple[str, dict[str, Any]]]:
    """Model properties in definition order, with the `kind` discriminator first."""
    props = schema.get("properties", {})
    names = list(props)
    if "kind" in names:
        names.remove("kind")
        names.insert(0, "kind")
    return [(name, props[name]) for name in names]


def _emit_interface(cls: type[BaseModel]) -> str:
    schema = cls.model_json_schema()
    required = set(schema.get("required", []))
    lines: list[str] = []
    description = schema.get("description")
    if description:
        lines.append(f"/** {description} */")
    lines.append(f"export interface {cls.__name__} {{")
    for name, prop in _ordered_properties(schema):
        token, nullable = _resolve_type(prop, where=f"{cls.__name__}.{name}")
        prop_description = prop.get("description")
        if prop_description:
            lines.append(f"  /** {prop_description} */")
        optional = "" if name == "kind" or name in required else "?"
        ts_type = _ts_type(token) + (" | null" if nullable else "")
        lines.append(f"  {name}{optional}: {ts_type};")
    lines.append("}")
    return "\n".join(lines)


def _emit_union(name: str, members: list[str]) -> str:
    lines = [f"export type {name} ="] + [f"  | {member}" for member in members]
    lines[-1] += ";"
    return "\n".join(lines)


def _metric_denominations(cls: type[BaseModel]) -> list[tuple[str, str]]:
    """Numeric metric fields with their denomination marker, in field order.

    Every int/float metric field must declare a denomination via
    `json_schema_extra={"denomination": ...}`; a missing or unknown value
    raises UnsupportedSchemaError so future kinds cannot forget it. Date
    fields and the `kind` discriminator carry no marker.
    """
    schema = cls.model_json_schema()
    fields: list[tuple[str, str]] = []
    for name, prop in _ordered_properties(schema):
        token, _ = _resolve_type(prop, where=f"{cls.__name__}.{name}")
        if token not in ("integer", "number"):
            continue
        denomination = prop.get("denomination")
        if denomination not in _DENOMINATIONS:
            raise UnsupportedSchemaError(
                f"{cls.__name__}.{name}: numeric metric field lacks a valid "
                f"denomination marker (expected one of {_DENOMINATIONS}, "
                f"got {denomination!r})"
            )
        fields.append((name, denomination))
    return fields


def _emit_metric_fields() -> str:
    lines = [
        "export const METRIC_FIELDS: Record<",
        "  ProductKind,",
        "  Record<string, { denomination: MetricDenomination }>",
        "> = {",
    ]
    for kind in PRODUCT_KINDS:
        fields = _metric_denominations(REGISTRY[kind].metrics_cls)
        if not fields:
            lines.append(f"  {kind}: {{}},")
            continue
        lines.append(f"  {kind}: {{")
        for name, denomination in fields:
            lines.append(f'    {name}: {{ denomination: "{denomination}" }},')
        lines.append("  },")
    lines.append("};")
    return "\n".join(lines)


def _emit_kind_info() -> str:
    lines = [
        "export const KIND_INFO: Record<",
        "  ProductKind,",
        "  {",
        '    role: "asset" | "liability" | "none";',
        '    balanceConvention: "value" | "available" | "owed" | "units" | "none";',
        "    labelEs: string;",
        "  }",
        "> = {",
    ]
    for kind in PRODUCT_KINDS:
        spec = REGISTRY[kind]
        label = json.dumps(spec.label_es, ensure_ascii=False)
        lines.append(
            f'  {kind}: {{ role: "{spec.role.value}", '
            f'balanceConvention: "{spec.balance_convention.value}", '
            f"labelEs: {label} }},"
        )
    lines.append("};")
    return "\n".join(lines)


def _render_index_ts() -> str:
    kinds_const = "\n".join(
        ["export const PRODUCT_KINDS = ["]
        + [f'  "{kind}",' for kind in PRODUCT_KINDS]
        + ["] as const;"]
    )
    blocks = [
        f"// {HEADER}",
        kinds_const,
        "export type ProductKind = (typeof PRODUCT_KINDS)[number];",
    ]
    for kind in PRODUCT_KINDS:
        spec = REGISTRY[kind]
        blocks.append(_emit_interface(spec.attributes_cls))
        blocks.append(_emit_interface(spec.metrics_cls))
    blocks.append(
        _emit_union(
            "ProductAttributes",
            [REGISTRY[kind].attributes_cls.__name__ for kind in PRODUCT_KINDS],
        )
    )
    blocks.append(
        _emit_union(
            "ProductMetrics",
            [REGISTRY[kind].metrics_cls.__name__ for kind in PRODUCT_KINDS],
        )
    )
    blocks.append(_emit_kind_info())
    blocks.append(
        "export type MetricDenomination = "
        + " | ".join(f'"{denomination}"' for denomination in _DENOMINATIONS)
        + ";"
    )
    blocks.append(_emit_metric_fields())
    blocks.append(
        "export const ASSET_KINDS: ProductKind[] = PRODUCT_KINDS.filter(\n"
        '  (kind) => KIND_INFO[kind].role === "asset",\n'
        ");"
    )
    blocks.append(
        "export const LIABILITY_KINDS: ProductKind[] = PRODUCT_KINDS.filter(\n"
        '  (kind) => KIND_INFO[kind].role === "liability",\n'
        ");"
    )
    return "\n\n".join(blocks) + "\n"


def _render_schema_json() -> str:
    models: list[type[BaseModel]] = [ScrapedProduct, ScrapedTransaction]
    for kind in PRODUCT_KINDS:
        models.append(REGISTRY[kind].attributes_cls)
        models.append(REGISTRY[kind].metrics_cls)
    _, defs = models_json_schema(
        [(model, "validation") for model in models],
        ref_template="#/$defs/{model}",
    )
    document = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "chanchito product model",
        "description": (
            "Ingest contract for scraped products and transactions; "
            "ScrapedProduct and ScrapedTransaction are the envelope models."
        ),
        "$defs": defs["$defs"],
    }
    return json.dumps(document, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def _md_table(cls: type[BaseModel], denominations: dict[str, str] | None = None) -> str:
    """Markdown field table; pass `denominations` to add the metrics column."""
    schema = cls.model_json_schema()
    required = set(schema.get("required", []))
    if denominations is None:
        lines = ["| Field | Type | Description |", "| --- | --- | --- |"]
    else:
        lines = [
            "| Field | Type | Denomination | Description |",
            "| --- | --- | --- | --- |",
        ]
    for name, prop in _ordered_properties(schema):
        token, _ = _resolve_type(prop, where=f"{cls.__name__}.{name}")
        optional = name != "kind" and name not in required
        type_str = _md_type(token) + ("?" if optional else "")
        description = prop.get("description", "")
        if denominations is None:
            lines.append(f"| `{name}` | `{type_str}` | {description} |")
        else:
            denomination = denominations.get(name, "")
            lines.append(
                f"| `{name}` | `{type_str}` | {denomination} | {description} |"
            )
    return "\n".join(lines)


_INTRO = """\
Every product row keeps a small set of **universal promoted columns** (id,
account, parent product, `kind`, `name`, `slug`, `currency`, `external_ref`,
`current_balance`, `balance_as_of`, `is_active`, `display_order`, timestamps).
Everything kind-specific lives in two validated JSONB payloads:

- **Attributes** — slow-changing identity/config (card last4, maturity dates,
  portfolio). Shallow-merged on write, so a scrape that only saw the dashboard
  can never wipe a field read earlier from a detail page.
- **Metrics** — one per-scrape observation (balance, available, owed, nav,
  units). Appended to snapshot history on change and denormalized as the
  latest value on the product; the writer promotes `metrics.headline()` into
  `current_balance` and stamps `balance_as_of` itself.

Promotion rationale: only universal fields get real columns. No kind-specific
field is aggregated in SQL (all product math lives in JS), so per-kind fields
stay in JSONB typed by this registry rather than widening the table per kind.
Scrapers submit data through the `ScrapedProduct` / `ScrapedTransaction`
envelopes — the generated JSON Schema is the future REST wire contract.

Conventions: snake_case keys; CLP amounts `int`, USD/crypto amounts `float`;
dates as ISO `YYYY-MM-DD` strings; percentages as percent numbers (4.2 = 4.2%).
Optional fields are marked `?`. Every numeric metric field declares a
denomination: `currency` (amount in the product's `currency` column,
convertible), `percent` (raw percent number), or `count` (raw unit count)."""


def _render_products_md() -> str:
    blocks = [f"<!-- {HEADER} -->", "# Product model", _INTRO]
    for kind in PRODUCT_KINDS:
        spec = REGISTRY[kind]
        blocks.append(f"## {spec.label_es} (`{kind}`)")
        blocks.append(
            f"Net-worth role: **{spec.role.value}** · "
            f"balance convention: **{spec.balance_convention.value}**"
        )
        blocks.append("### Attributes")
        blocks.append(_md_table(spec.attributes_cls))
        blocks.append("### Metrics")
        blocks.append(
            _md_table(
                spec.metrics_cls,
                denominations=dict(_metric_denominations(spec.metrics_cls)),
            )
        )
    return "\n\n".join(blocks) + "\n"


def generate(root: Path) -> None:
    """Write the three artifacts under `root` (a product-model package root)."""
    generated = root / "generated"
    generated.mkdir(parents=True, exist_ok=True)
    (generated / "product-model.schema.json").write_text(
        _render_schema_json(), encoding="utf-8"
    )
    (generated / "index.ts").write_text(_render_index_ts(), encoding="utf-8")
    (root / "PRODUCTS.md").write_text(_render_products_md(), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=PACKAGE_ROOT,
        help="Package root to write artifacts under (default: the real package).",
    )
    args = parser.parse_args()
    generate(args.out_dir)
    print(f"Wrote product-model artifacts under {args.out_dir}")


if __name__ == "__main__":
    main()
