"""Single source of truth for per-kind product payloads and ingest envelopes."""

from .attributes import (
    BankAccountAttributes,
    BaseAttributes,
    CardAttributes,
    CheckingAttributes,
    CreditCardAttributes,
    CryptoAttributes,
    DebitCardAttributes,
    InstallmentLoanAttributes,
    InvestmentAttributes,
    LineOfCreditAttributes,
    LoanAttributes,
    MortgageAttributes,
    OtherAttributes,
    PrepaidCardAttributes,
    RevolvingCreditAttributes,
    SavingsAttributes,
    TermDepositAttributes,
    VistaAttributes,
    WalletAttributes,
)
from .envelopes import ScrapedProduct, ScrapedTransaction
from .kinds import PRODUCT_KINDS, BalanceConvention, NetWorthRole, ProductKind
from .metrics import (
    BankAccountMetrics,
    BaseMetrics,
    CheckingMetrics,
    CreditCardMetrics,
    CryptoMetrics,
    DebitCardMetrics,
    InstallmentLoanMetrics,
    InvestmentMetrics,
    LineOfCreditMetrics,
    LoanMetrics,
    MortgageMetrics,
    OtherMetrics,
    PrepaidCardMetrics,
    RevolvingCreditMetrics,
    SavingsMetrics,
    TermDepositMetrics,
    VistaMetrics,
    WalletMetrics,
)
from .registry import REGISTRY, KindSpec, ProductAttributes, ProductMetrics

__all__ = [
    "PRODUCT_KINDS",
    "ProductKind",
    "NetWorthRole",
    "BalanceConvention",
    "BaseAttributes",
    "BankAccountAttributes",
    "CardAttributes",
    "RevolvingCreditAttributes",
    "InstallmentLoanAttributes",
    "CheckingAttributes",
    "SavingsAttributes",
    "VistaAttributes",
    "WalletAttributes",
    "TermDepositAttributes",
    "CreditCardAttributes",
    "DebitCardAttributes",
    "PrepaidCardAttributes",
    "LineOfCreditAttributes",
    "LoanAttributes",
    "MortgageAttributes",
    "InvestmentAttributes",
    "CryptoAttributes",
    "OtherAttributes",
    "BaseMetrics",
    "BankAccountMetrics",
    "RevolvingCreditMetrics",
    "InstallmentLoanMetrics",
    "CheckingMetrics",
    "SavingsMetrics",
    "VistaMetrics",
    "WalletMetrics",
    "TermDepositMetrics",
    "CreditCardMetrics",
    "DebitCardMetrics",
    "PrepaidCardMetrics",
    "LineOfCreditMetrics",
    "LoanMetrics",
    "MortgageMetrics",
    "InvestmentMetrics",
    "CryptoMetrics",
    "OtherMetrics",
    "KindSpec",
    "REGISTRY",
    "ProductAttributes",
    "ProductMetrics",
    "ScrapedProduct",
    "ScrapedTransaction",
]
